version: "3.8"

services:
  nats-server:
    image: nats:latest
  client-gateway:
    image: us-west1-docker.pkg.dev/microservices-devtallers/image-registry/client-gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
  products-ms:
    image: us-west1-docker.pkg.dev/microservices-devtallers/image-registry/products-ms
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    environment:
      - PORT=3000
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=${NATS_SERVERS}
  orders-ms:
    image: us-west1-docker.pkg.dev/microservices-devtallers/image-registry/orders-ms
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DB_URL}
      - NATS_SERVERS=${NATS_SERVERS}
  #------------------------------
  #  AUTH MICROSERVICE
  # ------------------------------
  auth-ms:
    image: us-west1-docker.pkg.dev/microservices-devtallers/image-registry/auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  # ------------------------------
  #  PAYMENTS MICROSERVICE
  # ------------------------------
  payments-ms:
    image: us-west1-docker.pkg.dev/microservices-devtallers/image-registry/payments-ms
    depends_on:
      - stripe-cli
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET=${PAYMENTS_MS_STRIPE_SECRET}
      - STRIPE_DEVICE_NAME=${PAYMENTS_MS_STRIPE_DEVICE_NAME}
      - STRIPE_URL_SECCESS=${PAYMENTS_MS_STRIPE_URL_SECCESS}
      - STRIPE_URL_CANCEL=${PAYMENTS_MS_STRIPE_URL_CANCEL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}
      - NATS_SERVERS=${NATS_SERVERS}
  # ------------------------------
  #  STRIPE CLI
  # ------------------------------
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${PAYMENTS_MS_STRIPE_SECRET} --device-name ${PAYMENTS_MS_STRIPE_DEVICE_NAME} --forward-to http://payments-ms:${PAYMENTS_MS_PORT}/payments/hook/"
