apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/microservices-devtallers/image-registry/payments-ms
        name: payments-ms
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_DEVICE_NAME
            value: Stripe_macos
          - name: STRIPE_URL_SECCESS
            value: "http://localhost:3004/payments/success"
          - name: STRIPE_URL_CANCEL
            value: "http://localhost:3004/payments/cancel"
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: STRIPE_ENDPOINT_SECRET
          - name: STRIPE_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: STRIPE_SECRET
        resources: {}
status: {}
